### ISSUE TITLE
如何应用到UTM坐标系下

### ISSUE THREAD

**Issue by Nisoka** [zm0612/eskf-gps-imu-fusion#12]
请问: 我考虑直接将GPS数据转化到UTM坐标系, 但是fuse.txt的结果跑飞了, gt.txt没问题
可能
1 是与init_pose_有关系, 
2 是UTM坐标系 是投影导致的?

谢谢

**Comment by zm0612** [comment]
hello，目前算法是基于GPS的经纬高数据，转到局部导航系NED使用的，没有对UTM直接进行支持。
