### ISSUE TITLE
该方法可能严重依赖速度的初值

### ISSUE THREAD

**Issue by shockjiang** [zm0612/eskf-gps-imu-fusion#14]
- 当使用 init_velocity_ = curr_gps_data.true_velocity; 的时候，结果图如文档所示
- 当将初始化速度设为0时， init_velocity_ = Eigen::Vector3d::Zero()，发现结果不是太好，偏差会有几十米

不知道是我的用法问题，还是程序对初值依赖的原因。

见图：

![image](https://user-images.githubusercontent.com/1284499/199200466-3276db2f-4cba-4f3d-98eb-d2e2f67f302b.png)

![image](https://user-images.githubusercontent.com/1284499/199200511-4d4b521b-91a5-4934-b6da-f6bc11ba957f.png)

**Comment by linfan68** [comment]
初始位置是不是也有类似的问题呢？有没有尝试一下不同的数据集？

**Comment by linfan68** [comment]
My results:
![image](https://user-images.githubusercontent.com/4918344/202236327-0c8794a0-5991-46b1-b084-ccfed8092426.png)
![image](https://user-images.githubusercontent.com/4918344/202236380-a95c8041-afca-4709-afc5-ee579db5c468.png)

With this change:
```C++
bool ESKF::Init(const GPSData &curr_gps_data, const IMUData &curr_imu_data) {
    // init_velocity_ = curr_gps_data.true_velocity;
    init_velocity_ = Eigen::Vector3d(0, 0, 0);
////
```

**Comment by zm0612** [comment]
如果初值的速度或者位置差的太远，会影响收敛的效果，你需要去根据实际情况进行调参。目前代码进行了更新，修复了一些bug，欢迎再次尝试

**Comment by JACKLiuDay** [comment]
> 如果初值的速度或者位置差的太远，会影响收敛的效果，你需要去根据实际情况进行调参。目前代码进行了更新，修复了一些bug，欢迎再次尝试

博主您好，如果我在实际应用中，gps无法获取到 true velocity，直接用imu的速度来作为初值可以吗

**Comment by zm0612** [comment]
> > 如果初值的速度或者位置差的太远，会影响收敛的效果，你需要去根据实际情况进行调参。目前代码进行了更新，修复了一些bug，欢迎再次尝试
> 
> 博主您好，如果我在实际应用中，gps无法获取到 true velocity，直接用imu的速度来作为初值可以吗

你好，imu+gps的系统多数情况下是一个收敛的系统，即使你给的初速度与真实速度有差距，系统运行一段时间也是会收敛的，如果你没有真实速度，最简单的方法，你把两个时刻的gps位置相减，然后除以时间，得到的速度作为初速度即可。另外IMU是一个测加速度的传感器，它本身无法得到速度的。

**Comment by JACKLiuDay** [comment]
> > > 如果初值的速度或者位置差的太远，会影响收敛的效果，你需要去根据实际情况进行调参。目前代码进行了更新，修复了一些bug，欢迎再次尝试
> > 
> > 
> > 博主您好，如果我在实际应用中，gps无法获取到 true velocity，直接用imu的速度来作为初值可以吗
> 
> 你好，imu+gps的系统多数情况下是一个收敛的系统，即使你给的初速度与真实速度有差距，系统运行一段时间也是会收敛的，如果你没有真实速度，最简单的方法，你把两个时刻的gps位置相减，然后除以时间，得到的速度作为初速度即可。另外IMU是一个测加速度的传感器，它本身无法得到速度的。

非常感谢您的回复，我会在自己的系统中尝试该方法

**Comment by hjwang1** [comment]
IMU的速度没有轮速计精确，融合后会也会好些发自我的手机-------- 原始邮件 --------发件人： Dayu ***@***.***>日期： 2023年12月22日周五 下午4:29收件人： zm0612/eskf-gps-imu-fusion ***@***.***>抄送： Subscribed ***@***.***>主    题： Re: [zm0612/eskf-gps-imu-fusion] 该方法可能严重依赖速度的初值 (Issue #14)

如果初值的速度或者位置差的太远，会影响收敛的效果，你需要去根据实际情况进行调参。目前代码进行了更新，修复了一些bug，欢迎再次尝试

博主您好，如果我在实际应用中，gps无法获取到 true velocity，直接用imu的速度来作为初值可以吗
