### ISSUE TITLE
线速度转到角速度处理这里是不是一个bug？

### ISSUE THREAD

**Issue by shockjiang** [zm0612/eskf-gps-imu-fusion#15]
这里：https://github.com/zm0612/eskf-gps-imu-fusion/blob/main/src/eskf.cpp#L194

`    
   constexpr double rm = 6353346.18315;
    constexpr double rn = 6384140.52699;
    Eigen::Vector3d w_en_n(-velocity_[1] / (rm + curr_gps_data_.position_lla[2]),
                           velocity_[0] / (rn + curr_gps_data_.position_lla[2]),
                           velocity_[0] / (rn + curr_gps_data_.position_lla[2])
                           * std::tan(curr_gps_data_.position_lla[0] * kDegree2Radian));
    Eigen::Vector3d w_in_n = w_en_n + w_;

`

w_en_n 的EU上的分量，是根据东向线速度转换的，它是平行于极轴的旋转分量，因此投影到EU上的分量，应该是：
velocity_[0] / (rn + curr_gps_data_.position_lla[2]) * std::sin(curr_gps_data_.position_lla[0] * kDegree2Radian)
和
velocity_[0] / (rn + curr_gps_data_.position_lla[2]) * std::cos(curr_gps_data_.position_lla[0] * kDegree2Radian)

**Comment by zm0612** [comment]
目前已经对代码进行了重构，坐标系统一到了NED，已经不再有这个问题了，感谢指正
