### ISSUE TITLE
encoder和imu的ESKF融合

### ISSUE THREAD

**Issue by chengwei0427** [zm0612/eskf-gps-imu-fusion#2]
楼主你好，
看了你的博客，受益匪浅；这里有个问题想请教一下；
我想使用encoder轮式里程计和imu进行融合，获取一个DR推导；请问有什么建议吗？
目前没有想好，该用哪些做预测，哪些做观测？
encoder反馈有位姿pose，线速度，角速度；imu反馈有线加速度和角速度，
感谢！

**Comment by zm0612** [comment]
你好，IMU+轮式里程计的融合，我没有做过，我之前看过一些论文有做这个的，建模挺细致的，可以搜一下相关的论文看一下
