### ISSUE TITLE
请问您提到的文章的DOI号是多少

### ISSUE THREAD

**Issue by TheSeanParker** [zm0612/eskf-gps-imu-fusion#20]
<<Observability Analysis of Piece-Wise Constant Systems>>
这篇文章,我查到了很多版本,方便您分享一下这个文章的DOI号么?
另外想请教的是Observability是观测性分析还是观测度分析?如果是前者,后者的文章,您有推荐么?

**Comment by zm0612** [comment]
参考论文DOI：https://doi.org/10.48550/arXiv.1711.02508
参考教材书名：《捷联惯导算法与组合导航原理》（严恭敏）
