### ISSUE TITLE
如果我的imu是ENU坐标系该怎么修改代码实现融合呢？

### ISSUE THREAD

**Issue by LIN-DN** [zm0612/eskf-gps-imu-fusion#22]

**Comment by zm0612** [comment]
IMU数据不存在ENU坐标系这种说法，IMU是Body坐标系，你只要确保你的IMU数据的Body系是前右下，就可以使用我的代码，不需要做改动，如果你的IMU坐标系是前左上，或者右前上，只需要通过将其变换到前右下即可。
