### ISSUE TITLE
仿真偏差较大

### ISSUE THREAD

**Issue by zhi-yuan-song** [zm0612/eskf-gps-imu-fusion#24]
您好，我从RTK上获取到相应的GPS数据和IMU加速度和角速度信息，RTK数据为真值，由此创建相应的文件信息。但是仿真结果不容乐观，请问该怎么修改呢？RKT [IMU的X轴朝车辆右方，Y轴朝车辆前方，Z轴朝上，输入时已经做了坐标转换。

**Comment by zm0612** [comment]
你好，整个系统导航系使用的是NED（北东地），IMU的body系是使用的前右下，最简单的办法就是你IMU的测量值按照下述方法去尝试转换：
you imu x -> i imu y  也就是你的IMU输出的x值，在我的系统中使用时，将其赋值给y
you imu y -> i imu x  也就是你的IMU输出的y值，在我的系统中使用时，将其赋值给x
you imu z -> i imu -z  z的测量值去反就行

注意：重力加速度可能是正g，也可能是负g，这个取决于你的IMU厂家定义，如果你按照上述方法改好之后，在高度方向上发散了，或者误差特别大，可以去尝试调试一下g值的正负号。

另外如果你的RTK精度比较高，尝试去修改GPS的噪声标准差，将其改小一些，对应的位置在此：https://github.com/zm0612/eskf-gps-imu-fusion/blob/a8acb6ae99b80223c12fd6690383d6755d05ff42/config/config.yaml#L21

也可以去尝试修改IMU的噪声标准差，在这里修改：https://github.com/zm0612/eskf-gps-imu-fusion/blob/a8acb6ae99b80223c12fd6690383d6755d05ff42/config/config.yaml#L17

卡尔曼的调参主要就是状态转移的噪声和测量噪声大小的调节。你可以去尝试一下。

如有问题，欢迎再次提出，如果实在效果不加，也可以把你的转好的格式的数据传上来，我帮你测试一下。
