### ISSUE TITLE
my_test.csv

### ISSUE THREAD

**Issue by lizhaoyang12344567** [zm0612/eskf-gps-imu-fusion#25]
ini lat (deg),ini lon (deg),ini alt (m),ini vx_body (m/s),ini vy_body (m/s),ini vz_body (m/s),ini yaw (deg),ini pitch (deg),ini roll (deg)
32,120,0,2,0,0,0,0,0
command type,yaw (deg),pitch (deg),roll (deg),vx_body (m/s),vy_body (m/s),vz_body (m/s),command duration (s),GPS visibility
1,0,5,0,0,0,0,10,1
1,0,0,0,0,0,0,10,1
1,0,-5,0,0,0,0,10,1
1,0,0,0,0,0,0,10,1
1,0,5,0,0,0,0,10,1
1,0,0,0,0,0,0,10,1
1,0,-5,0,0,0,0,10,1
1,0,0,0,0,0,0,10,1
1,0,0,0,0,0,0,10,1

**Comment by zm0612** [comment]
![image](https://github.com/zm0612/eskf-gps-imu-fusion/assets/43093566/fb73efa7-87d1-4e2b-83eb-b87bcb1db1f9)
