### ISSUE TITLE
可以使用ros订阅发布话题的形式，使用这套开源代码吗？

### ISSUE THREAD

**Issue by liutaosgsg** [zm0612/eskf-gps-imu-fusion#27]
如题，可以使用ros订阅发布话题的形式，使用这套开源代码吗？

**Comment by zm0612** [comment]
hello, 是可以的，这套算法的结构本身就是有做一些封装，你只需要修改最外层的数据输入，接入ros的回调即可。大致思路如下：
1. 删除这个函数 
https://github.com/zm0612/eskf-gps-imu-fusion/blob/da93afa7864e3fde7c5241f2babc8cab5ab13fc0/src/eskf_flow.cpp#L116
3. ros回调函数中IMU和GPS的数据分别缓存到下面两个变量里面：
https://github.com/zm0612/eskf-gps-imu-fusion/blob/da93afa7864e3fde7c5241f2babc8cab5ab13fc0/include/eskf_flow.h#L70

**Comment by liutaosgsg** [comment]
1、应该是run里面的 ReadData(); 不是testrun里面的。
2、 应该是缓存到这个buffer里面把。   
std::deque<IMUData> imu_data_buff_;
    std::deque<GPSData> gps_data_buff_;

**Comment by zm0612** [comment]
你说的是对的，不好意思，我指错了地方

**Comment by liutaosgsg** [comment]
哦哦，您好，testrun，这个函数还具备只预测imu轨迹的功能吗？我看了下里面是误差卡尔曼的功能。

**Comment by zm0612** [comment]
testrun早期写的时候，主要就是用来测试的，可以直接从这个开始看就行：
https://github.com/zm0612/eskf-gps-imu-fusion/blob/da93afa7864e3fde7c5241f2babc8cab5ab13fc0/src/eskf_flow.cpp#L50C18-L50C18

**Comment by liutaosgsg** [comment]
/使用该函数时相当于只使用IMU位姿解算
//    eskf_flow.TestRun();//only predict
我看写了这段话，现在还有这个功能吗？这个是通过IMU来预测位姿？预测平移和旋转？

**Comment by zm0612** [comment]
> /使用该函数时相当于只使用IMU位姿解算 // eskf_flow.TestRun();//only predict 我看写了这段话，现在还有这个功能吗？这个是通过IMU来预测位姿？预测平移和旋转？

是的
