### ISSUE TITLE
请问作者实验时用的GPS模块和IMU模块是什么型号的呢？

### ISSUE THREAD

**Issue by ideafold** [zm0612/eskf-gps-imu-fusion#3]
如题。

另外，对于普通双频GPS模块，非差分类型，适合做eskf吗？ 普通双频GPS的定位精度相对于来说比较差一些，开放天空1.x米的定位精度水平。

**Comment by zm0612** [comment]
你好，我这里仓库中使用的是仿真数据进行测试的，使用的仿真工具是：[gnss-ins-sim](https://github.com/Aceinna/gnss-ins-sim)

我印象中普通的GPS定位精度能达到5~10米，这种其实非常适合做gps和imu的融合，如果是差分的GPS精度已经非常高了，做融合实际提升并不大。

另外我这个仓库中的仿真实验就是一个平均误差5m的gps与一个中等精度的IMU融合的结果，可以看到readme中图片显示的效果，精度提升比较明显。

**Comment by chenci** [comment]
imu的ba, bg大概在什么水平？
