### ISSUE TITLE
您好，想问下真值gt是怎么提供的

### ISSUE THREAD

**Issue by JACKLiuDay** [zm0612/eskf-gps-imu-fusion#31]
您好，感谢您分享的开源ESKF工程，我打算用ros实现该工程，对于博客中提到的gt真值，请问是如何提供的，是依靠仿真数据吗，有没有在实物上做过gt的采集和测试，我们打算用自己的RTK设备试试。

**Comment by zm0612** [comment]
你好，我主要是在仿真数据上进行的测试，仓库中提供的数据来自[gnss-ins-sim](https://github.com/Aceinna/gnss-ins-sim)，GT也是该仿真工具提供的。如果你想替换成自己RTK采集的数据，只需要按照格式写到对应的文件中即可。

**Comment by JACKLiuDay** [comment]
> 你好，我主要是在仿真数据上进行的测试，仓库中提供的数据来自[gnss-ins-sim](https://github.com/Aceinna/gnss-ins-sim)，GT也是该仿真工具提供的。如果你想替换成自己RTK采集的数据，只需要按照格式写到对应的文件中即可。

非常感谢您的回复

**Comment by JACKLiuDay** [comment]
> 你好，我主要是在仿真数据上进行的测试，仓库中提供的数据来自[gnss-ins-sim](https://github.com/Aceinna/gnss-ins-sim)，GT也是该仿真工具提供的。如果你想替换成自己RTK采集的数据，只需要按照格式写到对应的文件中即可。

你好，我想问下，如果我不想计算 地球自转引起的转动角速度变化，predict那部分直接把 w_in赋值为0 0 0 可以吗

**Comment by zm0612** [comment]
> > 你好，我主要是在仿真数据上进行的测试，仓库中提供的数据来自[gnss-ins-sim](https://github.com/Aceinna/gnss-ins-sim)，GT也是该仿真工具提供的。如果你想替换成自己RTK采集的数据，只需要按照格式写到对应的文件中即可。
> 
> 你好，我想问下，如果我不想计算 地球自转引起的转动角速度变化，predict那部分直接把 w_in赋值为0 0 0 可以吗

你好，你也可以把config文件中的这个标志位改成false
https://github.com/zm0612/eskf-gps-imu-fusion/blob/da93afa7864e3fde7c5241f2babc8cab5ab13fc0/config/config.yaml#L30C18-L30C18

**Comment by JACKLiuDay** [comment]
> > > 你好，我主要是在仿真数据上进行的测试，仓库中提供的数据来自[gnss-ins-sim](https://github.com/Aceinna/gnss-ins-sim)，GT也是该仿真工具提供的。如果你想替换成自己RTK采集的数据，只需要按照格式写到对应的文件中即可。
> > 
> > 
> > 你好，我想问下，如果我不想计算 地球自转引起的转动角速度变化，predict那部分直接把 w_in赋值为0 0 0 可以吗
> 
> 你好，你也可以把config文件中的这个标志位改成false
> 
> https://github.com/zm0612/eskf-gps-imu-fusion/blob/da93afa7864e3fde7c5241f2babc8cab5ab13fc0/config/config.yaml#L30

非常感谢您的回复，我会尝试进行测试

**Comment by hjwang1** [comment]
RTK可以采集数据做gt发自我的手机-------- 原始邮件 --------发件人： Dayu ***@***.***>日期： 2023年12月21日周四 上午9:42收件人： zm0612/eskf-gps-imu-fusion ***@***.***>抄送： Subscribed ***@***.***>主    题： [zm0612/eskf-gps-imu-fusion] 您好，想问下真值gt是怎么提供的 (Issue #31)
您好，感谢您分享的开源ESKF工程，我打算用ros实现该工程，对于博客中提到的gt真值，请问是如何提供的，是依靠仿真数据吗，有没有在实物上做过gt的采集和测试，我们打算用自己的RTK设备试试。
