### ISSUE TITLE
您好，ESKF的系统进入收敛状态该如何判断

### ISSUE THREAD

**Issue by JACKLiuDay** [zm0612/eskf-gps-imu-fusion#32]
您好，非常感谢您分享的优秀项目。我们在自己的工程上实现了非常好的应用效果，但是在系统初始化阶段，轨迹是会有一定漂移的，那我们该如何去判断ESKF达到了收敛的状态，也就是说当前融合的轨迹趋于稳定了呢？

**Comment by zm0612** [comment]
hello，初始化的时候漂移，可能是由于初始速度的设置存在误差，但是系统运行一段时间就会收敛。ESKF的状态的收敛我倒是没有在项目里过多的关注，只能从一些实验中给予你一些思路。对于IMU+GPS的系统，系统在一定运行条件下，会有一些状态量不可观，也就是说可能一直都不会收敛。可以参考我博客里面做的可观测性分析，在博客https://blog.csdn.net/u011341856/article/details/114262451?spm=1001.2014.3001.5501的“2.4 可观测性和可观测度分析“。另外如果系统运行状态多样的话，包括加减速，转弯等动作，系统是可以比较快速收敛到一个比较好的状态，此时可以通过P矩阵的数值来进行判断。如果系统收敛比较好的话，P矩阵会维持在一个比较好的范围内。

**Comment by JACKLiuDay** [comment]
> hello，初始化的时候漂移，可能是由于初始速度的设置存在误差，但是系统运行一段时间就会收敛。ESKF的状态的收敛我倒是没有在项目里过多的关注，只能从一些实验中给予你一些思路。对于IMU+GPS的系统，系统在一定运行条件下，会有一些状态量不可观，也就是说可能一直都不会收敛。可以参考我博客里面做的可观测性分析，在博客https://blog.csdn.net/u011341856/article/details/114262451?spm=1001.2014.3001.5501 的“2.4 可观测性和可观测度分析“。另外如果系统运行状态多样的话，包括加减速，转弯等动作，系统是可以比较快速收敛到一个比较好的状态，此时可以通过P矩阵的数值来进行判断。如果系统收敛比较好的话，P矩阵会维持在一个比较好的范围内。

非常感谢您的回复，我会尝试在工程里进行复现。
