### ISSUE TITLE
实际测量数据无法正常运行代码

### ISSUE THREAD

**Issue by Ec1ipse1** [zm0612/eskf-gps-imu-fusion#36]
![QQ截图20240418102347](https://github.com/zm0612/eskf-gps-imu-fusion/assets/158056849/cb026e75-9dd1-4312-a0d9-cf74ccf8ff79)
[测量数据.zip](https://github.com/zm0612/eskf-gps-imu-fusion/files/15019194/default.zip)

**Comment by zm0612** [comment]
ref_gps.csv文件的1697行，检查一下数据的完整性！

另外，我测试了你提供的数据，你采集的数据和我所用的坐标系可能不一致，可以检查一下你的重力加速度，另外你需要对传感器的外参数进行确认。

**Comment by Ec1ipse1** [comment]
谢谢你，ref_gps.csv补充后可以运行，但结果有些问题，可以加个qq详细沟通一下吗？有偿。十分感谢！qq:1103015077

**Comment by zm0612** [comment]
已加你，为了保护你的隐私，我将你上一条包含个人信息的回复删除了。
