### ISSUE TITLE
关于能否出一个ROS版本的demo

### ISSUE THREAD

**Issue by haohaoalt** [zm0612/eskf-gps-imu-fusion#37]
感谢大佬的工作，有代码也有解释。
为了进一步让更多做IMU GPS SLAM Robot的同学能够了解并使用ESKF
可不可以出一个ROS的版本，数据不使用gins-sim的仿真数据，而是使用不同人自己录制的bag数据（/imu, /gps）
感谢🙏

**Comment by haohaoalt** [comment]
一个可参考的示例如下：
https://github.com/zouyajing/imu_gnss_eskf

**Comment by zm0612** [comment]
hello，感谢关注，暂时还没有支持ros的计划。引入ros会导致项目的复杂度变高，不利于初学者的学习。

另外，代码本身耦合程度较低，你可以直接将核心代码拷贝到你的ros项目中，这个过程不会太复杂。
