### ISSUE TITLE
gps数据中的velocity 是NED 坐标系的，而imu数据Body frame的，为何他们可以共用一个TransformCoordinate转换函数呢？

### ISSUE THREAD

**Issue by ideafold** [zm0612/eskf-gps-imu-fusion#5]
GPS数据：
True GPS position/velocity, ['rad', 'rad', 'm', 'm/s', 'm/s', 'm/s'] for NED (LLA)

imu数据：
'ref_gyro'	True angular velocity in the body frame, units: ['rad/s', 'rad/s', 'rad/s']
'ref_accel'	True acceleration in the body frame, units: ['m/s^2', 'm/s^2', 'm/s^2']
The body coordinate system is fixed at the device. Its origin is located at the center of device. Its x axis points forward, lying in the symmetric plane of the device. Its y axis points to the right side of the device. Its z axis points downward to complete the right-hand coordinate system.

目标看起来是要都转换到ENU坐标系下。
但gps数据中的velocity 是NED 坐标系的，而imu数据Body frame的，为何他们可以共用一个TransformCoordinate转换函数呢？

**Comment by shockjiang** [comment]
@ideafold 请问关于坐标系的问题梳理清楚了吗？我遇到了类似的困惑。

**Comment by zm0612** [comment]
@shockjiang @ideafold  hello，目前对代码进行了整理，坐标系统一到了NED。
