### ISSUE TITLE
imu和gps模拟手机的姿态和位置

### ISSUE THREAD

**Issue by wei-kris** [zm0612/eskf-gps-imu-fusion#8]
您好 ，我看到您对通过imu和gps传感器模拟定位有很多经验 ，我有一个问题很困扰想从您这得到帮助。
我是游戏开发工程师 ，希望通过手机的imu和gps模拟手机的姿态和位置出现在unity(游戏引擎)中的地图上行驶。     但是我根据imu的横摆角来模拟时和gps经纬发生了很大的偏离 ，您是否有使用gps来纠正imu yaw角 来修正朝向的经验？  我希望能够及时的响应imu的朝向 ，但不要偏离gps位置太多 。
![image](https://user-images.githubusercontent.com/704748/160768178-bbe7f636-45c9-4dba-be78-b1515bbb3d27.png)
黄色箭头是gps位置，红色箭头是根据imu航向和速度模拟的，朝向偏差导致分道扬镳了。

**Comment by wei-kris** [comment]
我需要的可能不是根据imu得到一个更精准的经纬 ，而是通过gps修正 imu的偏差 。

**Comment by zhangzm0612** [comment]
不好意思，您的问题我没有太看明白。

看起来像是由于两个坐标系不统一导致imu在自己的坐标系中，而gps也在自己的坐标系中运动，它们分道扬镳是必然的。

另外imu是一种瞬时测量的传感器，你根据它进行短时间的位置和角度的积分，是可以的，但是只要超过一定的时间，误差就会变得越来越大，根据我的经验类似于手机这种消费级的imu，维持最多也就十几秒钟，误差发散的非常快，后面会越来越偏

**Comment by wei-kris** [comment]
@zhangzm0612  感谢回复 ，他们是统一的坐标系 ，黄色箭头是gps的经纬度转换出来的位置 ，而红色箭头是通过imu yaw角和gps的速度模拟运动后的位置 。   可以看到他们再运动一段时间后原来越远 ，这可能是因为imu的yaw不准确导致的。      
我不知道改如何观测gps，来让imu模拟运动回到正确的经纬位置上 ，我搜索到了很多EKF的解决方案 ，但是我对他们的理解很少 ，我不知道EKF是否能解决我的问题 。

**Comment by zm0612** [comment]
如果你方便的话，可以把你的如果利用IMU和GPS的数据进行轨迹计算的思路描述一下，以及你的具体需求描述一下，这样我可以更好的理解这个问题，给你一些思路

**Comment by wei-kris** [comment]
@zm0612 感谢 ，我当前是利用实时获取手机IMU的YAW作为航向，然后使用GPS的速度来移动， 当前使用GPS经纬只做了初始化位置 ，之后就没有使用到经纬数据了 。  希望通过这样的方式来模拟汽车( 现在是手机 )的运动。
这样的问题很明显，因为IMU的惯性等等问题航向不会那么准确 ， 也就会出现偏离道路的情况 ， 现在我希望能够利用到GPS经纬数据来把航向、位置修正回来 ，但是我没有思路如何做这件事。
任何帮助不胜感激。

**Comment by zm0612** [comment]
@wei-kris 你的问题我大概了解了，首先你这里有一个误解，IMU是测量不到YAW角的，因为你的手机是九轴的IMU，实际它是一个六轴的IMU加一个三轴的磁力计。这里需要强调的是你的这个YAW是通过磁力计获得的，磁力计测量得到的YAW角并不是一个累计的量，如果是以磁力计得到的YAW角，它不会随着时间的推移出现误差发散。

实际上你这里的问题是一个数据融合的问题，你需要将磁力计和GPS进行融合，最终你要得到的是融合之后的YAW角，也就是一个更加准确的YAW角。

这个问题确实可以通过卡尔曼滤波进行融合，而且也并不是很复杂。但是我并没有做过着相关的研究，不确定这样做的可行性。在我的印象中手机的罗盘，也就是磁力计实际上还是挺准的，我倒是没有注意到它会误差越来越大，至少我的用手机导航的时候方向还是挺对的。
