### ISSUE TITLE
pdf version of blog post

### ISSUE THREAD

**Issue by iceberg1369** [zm0612/eskf-gps-imu-fusion#9]
it is not easy for foreigners to read csdn blog post (https://blog.csdn.net/u011341856/article/details/114262451).
it is good to include a PDF version of blog in repo

**Comment by zm0612** [comment]
Received, I will provide a pdf version later！ thx @iceberg1369

**Comment by zm0612** [comment]
[eskf-blog.pdf](https://github.com/zm0612/eskf-gps-imu-fusion/files/13112802/eskf-blog.pdf)
 @iceberg1369
